In [1]:
import pandas as pd

In [26]:
df=pd.read_csv("D:\Airbnb Project\calendar.csv")

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\rishabh hinduja\AppData\Local\Temp\ipykernel_24368\2697070944.py:1: SyntaxWarning: invalid escape sequence '\A'
  df=pd.read_csv("D:\Airbnb Project\calendar.csv")

In [3]:
df

         listing_id        date available  minimum_nights  maximum_nights
0           1069572  2026-03-22         f               3            1125
1           1069572  2026-03-23         t               3            1125
2           1069572  2026-03-24         t               3            1125
3           1069572  2026-03-25         t               3            1125
4           1069572  2026-03-26         t               3            1125
...             ...         ...       ...             ...             ...
5879055     2180003  2027-03-17         t               3             150
5879056     2180003  2027-03-18         t               3             150
5879057     2180003  2027-03-19         t               3             150
5879058     2180003  2027-03-20         t               3             150
5879059     2180003  2027-03-21         t               3             150

[5879060 rows x 5 columns]

In [4]:
df=df.drop_duplicates()

In [5]:
df

         listing_id        date available  minimum_nights  maximum_nights
0           1069572  2026-03-22         f               3            1125
1           1069572  2026-03-23         t               3            1125
2           1069572  2026-03-24         t               3            1125
3           1069572  2026-03-25         t               3            1125
4           1069572  2026-03-26         t               3            1125
...             ...         ...       ...             ...             ...
5879055     2180003  2027-03-17         t               3             150
5879056     2180003  2027-03-18         t               3             150
5879057     2180003  2027-03-19         t               3             150
5879058     2180003  2027-03-20         t               3             150
5879059     2180003  2027-03-21         t               3             150

[5879060 rows x 5 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5879060 entries, 0 to 5879059
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   minimum_nights  int64
 4   maximum_nights  int64
dtypes: int64(3), object(2)
memory usage: 224.3+ MB

In [9]:
df.head(500)

     listing_id        date available  minimum_nights  maximum_nights
0       1069572  2026-03-22         f               3            1125
1       1069572  2026-03-23         t               3            1125
2       1069572  2026-03-24         t               3            1125
3       1069572  2026-03-25         t               3            1125
4       1069572  2026-03-26         t               3            1125
5       1069572  2026-03-27         f               3            1125
6       1069572  2026-03-28         f               3            1125
7       1069572  2026-03-29         f               3            1125
8       1069572  2026-03-30         f               3            1125
9       1069572  2026-03-31         f               3            1125
10      1069572  2026-04-01         f               3            1125
11      1069572  2026-04-02         f               3            1125
12      1069572  2026-04-03         f               3            1125
13      1069572  2026-04-04         f               3            1125
14      1069572  2026-04-05         f               3            1125
15      1069572  2026-04-06         f               3            1125
16      1069572  2026-04-07         f               3            1125
17      1069572  2026-04-08         f               3            1125
18      1069572  2026-04-09         t               3            1125
19      1069572  2026-04-10         t               3            1125
20      1069572  2026-04-11         f               3            1125
21      1069572  2026-04-12         f               3            1125
22      1069572  2026-04-13         f               3            1125
23      1069572  2026-04-14         f               3            1125
24      1069572  2026-04-15         f               3            1125
25      1069572  2026-04-16         t               3            1125
26      1069572  2026-04-17         f               3            1125
27      1069572  2026-04-18         f               3            1125
28      1069572  2026-04-19         f               3            1125
29      1069572  2026-04-20         f               3            1125
30      1069572  2026-04-21         f               3            1125
31      1069572  2026-04-22         f               3            1125
32      1069572  2026-04-23         f               3            1125
33      1069572  2026-04-24         f               3            1125
34      1069572  2026-04-25         f               3            1125
35      1069572  2026-04-26         f               3            1125
36      1069572  2026-04-27         t               3            1125
37      1069572  2026-04-28         t               3            1125
38      1069572  2026-04-29         t               3            1125
39      1069572  2026-04-30         f               3            1125
40      1069572  2026-05-01         f               3            1125
41      1069572  2026-05-02         f               3            1125
42      1069572  2026-05-03         f               3            1125
43      1069572  2026-05-04         f               3            1125
44      1069572  2026-05-05         f               3            1125
45      1069572  2026-05-06         f               3            1125
46      1069572  2026-05-07         t               3            1125
47      1069572  2026-05-08         f               3            1125
48      1069572  2026-05-09         f               3            1125
49      1069572  2026-05-10         f               3            1125
50      1069572  2026-05-11         f               3            1125
51      1069572  2026-05-12         t               3            1125
52      1069572  2026-05-13         t               3            1125
53      1069572  2026-05-14         f               3            1125
54      1069572  2026-05-15         f               3            1125
55      1069572  2026-05-16         f               3            1125
56      1069572  2026-05-17         f               3            1125
57      1069572  2026-05-18         f               3            1125
58      1069572  2026-05-19         f               3            1125
59      1069572  2026-05-20         f               3            1125
60      1069572  2026-05-21         f               3            1125
61      1069572  2026-05-22         f               3            1125
62      1069572  2026-05-23         f               3            1125
63      1069572  2026-05-24         f               3            1125
64      1069572  2026-05-25         f               3            1125
65      1069572  2026-05-26         f               3            1125
66      1069572  2026-05-27         f               3            1125
67      1069572  2026-05-28         f               3            1125
68      1069572  2026-05-29         f               3            1125
69      1069572  2026-05-30         t               3            1125
70      1069572  2026-05-31         f               3            1125
71      1069572  2026-06-01         f               3            1125
72      1069572  2026-06-02         f               3            1125
73      1069572  2026-06-03         f               3            1125
74      1069572  2026-06-04         t               3            1125
75      1069572  2026-06-05         f               3            1125
76      1069572  2026-06-06         f               3            1125
77      1069572  2026-06-07         f               3            1125
78      1069572  2026-06-08         f               3            1125
79      1069572  2026-06-09         f               3            1125
80      1069572  2026-06-10         f               3            1125
81      1069572  2026-06-11         f               3            1125
82      1069572  2026-06-12         f               3            1125
83      1069572  2026-06-13         f               3            1125
84      1069572  2026-06-14         f               3            1125
85      1069572  2026-06-15         f               3            1125
86      1069572  2026-06-16         f               3            1125
87      1069572  2026-06-17         t               3            1125
88      1069572  2026-06-18         f               3            1125
89      1069572  2026-06-19         f               3            1125
90      1069572  2026-06-20         f               3            1125
91      1069572  2026-06-21         t               3            1125
92      1069572  2026-06-22         t               3            1125
93      1069572  2026-06-23         t               3            1125
94      1069572  2026-06-24         t               3            1125
95      1069572  2026-06-25         t               3            1125
96      1069572  2026-06-26         f               3            1125
97      1069572  2026-06-27         f               3            1125
98      1069572  2026-06-28         f               3            1125
99      1069572  2026-06-29         t               3            1125
100     1069572  2026-06-30         f               3            1125
101     1069572  2026-07-01         f               3            1125
102     1069572  2026-07-02         f               3            1125
103     1069572  2026-07-03         f               3            1125
104     1069572  2026-07-04         f               3            1125
105     1069572  2026-07-05         f               3            1125
106     1069572  2026-07-06         t               3            1125
107     1069572  2026-07-07         t               3            1125
108     1069572  2026-07-08         f               3            1125
109     1069572  2026-07-09         t               3            1125
110     1069572  2026-07-10         t               3            1125
111     1069572  2026-07-11         f               3            1125
112     1069572  2026-07-12         t               3            1125
113     1069572  2026-07-13         t               3            1125
114     1069572  2026-07-14         t               3            1125
115     1069572  2026-07-15         t               3            1125
116     1069572  2026-07-16         t               3            1125
117     1069572  2026-07-17         t               3            1125
118     1069572  2026-07-18         t               3            1125
119     1069572  2026-07-19         t               3            1125
120     1069572  2026-07-20         t               3            1125
121     1069572  2026-07-21         t               3            1125
122     1069572  2026-07-22         t               3            1125
123     1069572  2026-07-23         t               3            1125
124     1069572  2026-07-24         t               3            1125
125     1069572  2026-07-25         f               3            1125
126     1069572  2026-07-26         f               3            1125
127     1069572  2026-07-27         f               3            1125
128     1069572  2026-07-28         f               3            1125
129     1069572  2026-07-29         t               3            1125
130     1069572  2026-07-30         t               3            1125
131     1069572  2026-07-31         t               3            1125
132     1069572  2026-08-01         t               3            1125
133     1069572  2026-08-02         t               3            1125
134     1069572  2026-08-03         t               3            1125
135     1069572  2026-08-04         f               3            1125
136     1069572  2026-08-05         f               3            1125
137     1069572  2026-08-06         f               3            1125
138     1069572  2026-08-07         f               3            1125
139     1069572  2026-08-08         f               3            1125
140     1069572  2026-08-09         t               3            1125
141     1069572  2026-08-10         t               3            1125
142     1069572  2026-08-11         t               3            1125
143     1069572  2026-08-12         t               3            1125
144     1069572  2026-08-13         t               3            1125
145     1069572  2026-08-14         t               3            1125
146     1069572  2026-08-15         t               3            1125
147     1069572  2026-08-16         t               3            1125
148     1069572  2026-08-17         t               3            1125
149     1069572  2026-08-18         t               3            1125
150     1069572  2026-08-19         t               3            1125
151     1069572  2026-08-20         t               3            1125
152     1069572  2026-08-21         t               3            1125
153     1069572  2026-08-22         t               3            1125
154     1069572  2026-08-23         t               3            1125
155     1069572  2026-08-24         t               3            1125
156     1069572  2026-08-25         t               3            1125
157     1069572  2026-08-26         t               3            1125
158     1069572  2026-08-27         t               3            1125
159     1069572  2026-08-28         t               3            1125
160     1069572  2026-08-29         t               3            1125
161     1069572  2026-08-30         t               3            1125
162     1069572  2026-08-31         t               3            1125
163     1069572  2026-09-01         t               3            1125
164     1069572  2026-09-02         f               3            1125
165     1069572  2026-09-03         f               3            1125
166     1069572  2026-09-04         f               3            1125
167     1069572  2026-09-05         f               3            1125
168     1069572  2026-09-06         f               3            1125
169     1069572  2026-09-07         f               3            1125
170     1069572  2026-09-08         f               3            1125
171     1069572  2026-09-09         t               3            1125
172     1069572  2026-09-10         t               3            1125
173     1069572  2026-09-11         t               3            1125
174     1069572  2026-09-12         t               3            1125
175     1069572  2026-09-13         t               3            1125
176     1069572  2026-09-14         t               3            1125
177     1069572  2026-09-15         t               3            1125
178     1069572  2026-09-16         t               3            1125
179     1069572  2026-09-17         t               3            1125
180     1069572  2026-09-18         t               3            1125
181     1069572  2026-09-19         t               3            1125
182     1069572  2026-09-20         t               3            1125
183     1069572  2026-09-21         t               3            1125
184     1069572  2026-09-22         t               3            1125
185     1069572  2026-09-23         t               3            1125
186     1069572  2026-09-24         t               3            1125
187     1069572  2026-09-25         t               3            1125
188     1069572  2026-09-26         f               3            1125
189     1069572  2026-09-27         t               3            1125
190     1069572  2026-09-28         f               3            1125
191     1069572  2026-09-29         t               3            1125
192     1069572  2026-09-30         t               3            1125
193     1069572  2026-10-01         t               3            1125
194     1069572  2026-10-02         t               3            1125
195     1069572  2026-10-03         t               3            1125
196     1069572  2026-10-04         t               3            1125
197     1069572  2026-10-05         t               3            1125
198     1069572  2026-10-06         t               3            1125
199     1069572  2026-10-07         f               3            1125
200     1069572  2026-10-08         f               3            1125
201     1069572  2026-10-09         f               3            1125
202     1069572  2026-10-10         t               3            1125
203     1069572  2026-10-11         t               3            1125
204     1069572  2026-10-12         t               3            1125
205     1069572  2026-10-13         t               3            1125
206     1069572  2026-10-14         t               3            1125
207     1069572  2026-10-15         t               3            1125
208     1069572  2026-10-16         t               3            1125
209     1069572  2026-10-17         t               3            1125
210     1069572  2026-10-18         t               3            1125
211     1069572  2026-10-19         t               3            1125
212     1069572  2026-10-20         t               3            1125
213     1069572  2026-10-21         t               3            1125
214     1069572  2026-10-22         t               3            1125
215     1069572  2026-10-23         t               3            1125
216     1069572  2026-10-24         t               3            1125
217     1069572  2026-10-25         t               3            1125
218     1069572  2026-10-26         t               3            1125
219     1069572  2026-10-27         t               3            1125
220     1069572  2026-10-28         t               3            1125
221     1069572  2026-10-29         t               3            1125
222     1069572  2026-10-30         t               3            1125
223     1069572  2026-10-31         t               3            1125
224     1069572  2026-11-01         t               3            1125
225     1069572  2026-11-02         t               3            1125
226     1069572  2026-11-03         t               3            1125
227     1069572  2026-11-04         t               3            1125
228     1069572  2026-11-05         t               3            1125
229     1069572  2026-11-06         t               3            1125
230     1069572  2026-11-07         t               3            1125
231     1069572  2026-11-08         t               3            1125
232     1069572  2026-11-09         t               3            1125
233     1069572  2026-11-10         t               3            1125
234     1069572  2026-11-11         t               3            1125
235     1069572  2026-11-12         t               3            1125
236     1069572  2026-11-13         t               3            1125
237     1069572  2026-11-14         t               3            1125
238     1069572  2026-11-15         t               3            1125
239     1069572  2026-11-16         t               3            1125
240     1069572  2026-11-17         t               3            1125
241     1069572  2026-11-18         t               3            1125
242     1069572  2026-11-19         t               3            1125
243     1069572  2026-11-20         t               3            1125
244     1069572  2026-11-21         t               3            1125
245     1069572  2026-11-22         t               3            1125
246     1069572  2026-11-23         t               3            1125
247     1069572  2026-11-24         t               3            1125
248     1069572  2026-11-25         t               3            1125
249     1069572  2026-11-26         t               3            1125
250     1069572  2026-11-27         t               3            1125
251     1069572  2026-11-28         t               3            1125
252     1069572  2026-11-29         t               3            1125
253     1069572  2026-11-30         t               3            1125
254     1069572  2026-12-01         t               3            1125
255     1069572  2026-12-02         t               3            1125
256     1069572  2026-12-03         t               3            1125
257     1069572  2026-12-04         t               3            1125
258     1069572  2026-12-05         t               3            1125
259     1069572  2026-12-06         t               3            1125
260     1069572  2026-12-07         t               3            1125
261     1069572  2026-12-08         t               3            1125
262     1069572  2026-12-09         t               3            1125
263     1069572  2026-12-10         t               3            1125
264     1069572  2026-12-11         t               3            1125
265     1069572  2026-12-12         t               3            1125
266     1069572  2026-12-13         t               3            1125
267     1069572  2026-12-14         t               3            1125
268     1069572  2026-12-15         t               3            1125
269     1069572  2026-12-16         t               3            1125
270     1069572  2026-12-17         t               3            1125
271     1069572  2026-12-18         t               3            1125
272     1069572  2026-12-19         t               3            1125
273     1069572  2026-12-20         t               3            1125
274     1069572  2026-12-21         t               3            1125
275     1069572  2026-12-22         t               3            1125
276     1069572  2026-12-23         t               3            1125
277     1069572  2026-12-24         t               3            1125
278     1069572  2026-12-25         t               3            1125
279     1069572  2026-12-26         t               3            1125
280     1069572  2026-12-27         t               3            1125
281     1069572  2026-12-28         t               3            1125
282     1069572  2026-12-29         t               3            1125
283     1069572  2026-12-30         t               3            1125

In [8]:
pd.set_option('display.max.rows',500)

In [15]:
df

                  date available  minimum_nights  maximum_nights
listing_id
1069572     2026-03-22         f               3            1125
1069572     2026-03-23         t               3            1125
1069572     2026-03-24         t               3            1125
1069572     2026-03-25         t               3            1125
1069572     2026-03-26         t               3            1125
...                ...       ...             ...             ...
2180003     2027-03-17         t               3             150
2180003     2027-03-18         t               3             150
2180003     2027-03-19         t               3             150
2180003     2027-03-20         t               3             150
2180003     2027-03-21         t               3             150

[5879060 rows x 4 columns]

In [28]:
df[df['listing_id'].isnull()]

Empty DataFrame
Columns: [listing_id, date, available, minimum_nights, maximum_nights]
Index: []

In [45]:
df['date']=pd.to_datetime(df['date'],format='%dd%mm%yyyy')

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5879060 entries, 0 to 5879059
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            datetime64[ns]
 2   available       string
 3   minimum_nights  int64
 4   maximum_nights  int64
dtypes: datetime64[ns](1), int64(3), string(1)
memory usage: 224.3 MB

In [48]:
df['available']=df['available'].astype('string')

In [50]:
df.to_csv(r"D:\Airbnb Project\calendar_cleaned.csv", index=False)